import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Geist } from "next/font/google";
import "@/style/style.css";
import { SidebarLayoutProvider } from "@/context";
import AppShell from "@/components/layout/AppShell";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-public-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", jakarta.variable, "font-sans", geist.variable)}
      suppressHydrationWarning
    >
      <body>
        <SidebarLayoutProvider>
          <AppShell>
            {children}
          </AppShell>
        </SidebarLayoutProvider>
      </body>
    </html>
  );
};
